version: "3"
services:

  
  nginx:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - internal
    volumes:
      - ./html/:/var/www/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build:
      context: ./php
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./html/:/var/www/html/
    networks:
      - internal
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - internal
networks:
  internal: